version: 2
jobs:
  build:
    machine: true

    environment:
      TEST_REPORTS: /tmp/test-reports

    steps:
      - checkout

      - restore_cache:
          keys:
            - maven
            - embedded-rabbitmq

      - run:
          name: Install Erlang
          command: |
            sudo sh -c 'echo "deb https://packages.erlang-solutions.com/ubuntu $(lsb_release -sc) contrib" >> /etc/apt/sources.list.d/erlang.list'
            wget https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
            sudo apt-key add erlang_solutions.asc
            sudo apt-get update
            sudo apt-get install -y erlang
            erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell

      - run:
          mvn clean install
      - store_artifacts:
          path: ./erl_crash.dump

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - save_cache:
          key: maven
          paths:
            - ~/.m2

      - save_cache:
          key: embedded-rabbitmq
          paths:
            - ~/.embeddedrabbitmq

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build-deploy:
    jobs:
      - build